version: "3.7"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  server:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development

  blockchain:
    image: trufflesuite/ganache-cli
    ports:
      - "7545:7545"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: real_time_betting
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  oracle:
    build: ./oracle
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development

  analytics:
    build: ./analytics
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
